name: Build and Push Docker image
on: [push]
jobs:
  build:        
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Set up JDK Corretto 21
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 21
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install esbuild
      run: npm i -g esbuild
    - name: Install TypeScript compiler
      run: npm i -g typescript
    - name: Maven Build
      run: mvn -T 1C clean install -Dmaven.test.skip=true -DskipTests -Dmaven.javadoc.skip=true -Dlicense.skip=true -U
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image and push it
      run: |
        cd build/application
        docker build . --tag ghcr.io/${{ github.actor }}/dirigible:latest
        docker push ghcr.io/${{ github.actor }}/dirigible:latest      
