name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: iliyan-velichkov
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the Docker image
run: |
       docker build . --tag ghcr.io/iliyan-velichkov/dirigible:latest
       docker run ghcr.io/iliyan-velichkov/dirigible:latest
       docker push ghcr.io/iliyan-velichkov/dirigible:latest